### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by FarmTon** [A-KTO-Tbl/Blum#10]

**Comment by FarmTon** [comment]
![image](https://github.com/user-attachments/assets/635e756f-12ac-46cf-ab39-70c82f748bf0)

**Comment by A-KTO-Tbl** [comment]
папки .git нету, это говорит о том что скрипт не клонирован а скачат как архив, или ещё как то. нужно именно клонировать репо, так как скрипт проверяет наличие обнов через гит

**Comment by FarmTon** [comment]
> папки .git нету, это говорит о том что скрипт не клонирован а скачат как архив, или ещё как то. нужно именно клонировать репо, так как скрипт проверяет наличие обнов через гит

я этого не знала) спасибо
