### ISSUE TITLE
Какая-то ошибка

### ISSUE THREAD

**Issue by Ktyby21** [A-KTO-Tbl/Blum#11]
2024-08-25 03:19:08 | ⏳ | Следующий сбор: 2024-08-25 12:20:40! | Tryl
fatal: unable to access 'https://github.com/A-KTO-Tbl/Blum/': SSL connection timeout
fatal: unable to access 'https://github.com/A-KTO-Tbl/Blum/': Recv failure: Connection timed out
fatal: unable to access 'https://github.com/A-KTO-Tbl/Blum/': Send failure: Broken pipe
fatal: unable to access 'https://github.com/A-KTO-Tbl/Blum/': Send failure: Broken pipe
fatal: unable to access 'https://github.com/A-KTO-Tbl/Blum/': Send failure: Broken pipe
fatal: unable to access 'https://github.com/A-KTO-Tbl/Blum/': Send failure: Broken pipe
fatal: unable to access 'https://github.com/A-KTO-Tbl/Blum/': Send failure: Broken pipe

**Comment by Ktyby21** [comment]
Ошибка иногда выскакивает, ВПН нету, с другими вашими автоботами все нормально

**Comment by A-KTO-Tbl** [comment]
ну эти ошибки возникают только из-за ошибки подключения к гиту для проверки обновления, тут дело не в скрипте, а в интернете, может иногда происходят фризы и в этот момент скрипт пытается проверить обновление. так как с другими скриптами такого нет, то значит всё в порядке, иногда могут действительно происходят фризы, в целом в этом ничего страшного нет, так как повторно скрипт уже подключится и проверит
